# Generated by Django 4.2.6 on 2023-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='state',
            field=models.IntegerField(verbose_name='Состояние'),
        ),
    ]
