# Generated by Django 4.2.6 on 2023-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_assets_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='state',
            field=models.CharField(max_length=255, verbose_name='Состояние'),
        ),
    ]
