# Generated by Django 4.2.6 on 2023-10-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_assets_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Электронная почта')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Ключ подписи')),
                ('progress', models.CharField(max_length=255, null=True, verbose_name='Прогресс')),
                ('salt', models.CharField(max_length=255, null=True, verbose_name='Соль пароля')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Пароль')),
                ('lvl', models.CharField(max_length=255, null=True, verbose_name='Уровень')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('img', models.CharField(max_length=255, null=True, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.IntegerField(null=True, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='coin',
            field=models.CharField(max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender',
            field=models.IntegerField(null=True, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='state',
            field=models.IntegerField(null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sum',
            field=models.CharField(max_length=255, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.IntegerField(null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.IntegerField(null=True, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='exp',
            field=models.CharField(max_length=255, null=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='img',
            field=models.CharField(max_length=255, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='mod',
            field=models.CharField(max_length=255, null=True, verbose_name='Изменение'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='type',
            field=models.IntegerField(null=True, verbose_name='Тип изменения'),
        ),
    ]
